#import Exception
try:
    #raise Exception('abc')
    pass
except:
    print 'except catch '
else:
    print 'nothing error'
finally:
    print 'everything is over.'
